# Generated by Django 4.1.1 on 2022-12-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_empid_accountant_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
