# Generated by Django 4.1.1 on 2022-12-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_address_alter_teacher_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
