# Generated by Django 4.1.1 on 2022-12-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
