# Generated by Django 4.1.1 on 2022-12-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
