# Generated by Django 4.1.1 on 2022-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
