# Generated by Django 4.1.1 on 2022-12-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_current_status_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(),
        ),
    ]
